# AUTOGENERATED FROM 'app/queries/create_new_process_from_template.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateNewProcessFromTemplateResult(NoPydanticValidation):
    id: uuid.UUID


async def create_new_process_from_template(
    executor: edgedb.AsyncIOExecutor,
    *,
    login: str,
    department_id: uuid.UUID,
    priority_id: uuid.UUID,
    template_id: uuid.UUID,
    passport_ref: str,
) -> CreateNewProcessFromTemplateResult:
    return await executor.query_single(
        """\
        with 
          user := (select User filter .login = <str>$login),
          department := (select Department filter .id = <uuid>$department_id),
          priority := (select Priority filter .id = <uuid>$priority_id),
          template := (select Template filter .id = <uuid>$template_id),
          process := template.process,
          passport_ref := <str>$passport_ref

        select (
          insert Process {
            realiser := user,
            realiserGroup := department,
            priority := priority,
            title := passport_ref,
            processType := process.processType,
          }  
        ) {id};\
        """,
        login=login,
        department_id=department_id,
        priority_id=priority_id,
        template_id=template_id,
        passport_ref=passport_ref,
    )
