# AUTOGENERATED FROM 'app/queries/create_summary_right.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import edgedb


async def create_summary_right(
    executor: edgedb.AsyncIOExecutor,
    *,
    login: str,
    right_val: str,
) -> bool | None:
    return await executor.query_single(
        """\
        with user := (select User filter .login = <str>$login), 
        right_val := (select Right filter .value = <str>$right_val)

        select (
          true if right_val in user.rights else false
        );\
        """,
        login=login,
        right_val=right_val,
    )
