# AUTOGENERATED FROM 'app/queries/create_assigned_notifications.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateAssignedNotificationsResult(NoPydanticValidation):
    id: uuid.UUID


async def create_assigned_notifications(
    executor: edgedb.AsyncIOExecutor,
    *,
    node_id: uuid.UUID,
) -> list[CreateAssignedNotificationsResult]:
    return await executor.query(
        """\
        with node := (select Node filter .id = <uuid>$node_id),
          assigned := node.assigned,

        for i in assigned union (
          insert Notification {
            to_department := i,
            passed_node := node,
          }
        )\
        """,
        node_id=node_id,
    )
