# AUTOGENERATED FROM 'app/queries/get_user_by_login.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetUserByLoginResult(NoPydanticValidation):
    id: uuid.UUID
    login: str
    FIO: str | None
    rights: list[GetUserByLoginResultRightsItem]


@dataclasses.dataclass
class GetUserByLoginResultRightsItem(NoPydanticValidation):
    id: uuid.UUID
    value: str


async def get_user_by_login(
    executor: edgedb.AsyncIOExecutor,
    *,
    login: str,
) -> GetUserByLoginResult | None:
    return await executor.query_single(
        """\
        select User {
            login,
            FIO,
            rights: {value}
        } filter .login=<str>$login\
        """,
        login=login,
    )
