# AUTOGENERATED FROM 'app/queries/get_process_by_id.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetProcessByIdResult(NoPydanticValidation):
    head: GetProcessByIdResultHead | None
    id: uuid.UUID
    title: str
    nodes: list[GetProcessByIdResultNodesItem]
    realiser: GetProcessByIdResultNodesItemAssignedItemBoss | None
    realiserGroup: GetProcessByIdResultrealiserGroup | None
    priority: GetProcessByIdResultPriority | None
    passport_ref: str | None
    processType: GetProcessByIdResultprocessType | None


@dataclasses.dataclass
class GetProcessByIdResultHead(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class GetProcessByIdResultNodesItem(NoPydanticValidation):
    id: uuid.UUID
    title: str
    assigned: list[GetProcessByIdResultNodesItemAssignedItem]
    along: GetProcessByIdResultNodesItemAlong | None
    addenable: bool | None
    subs: list[GetProcessByIdResultNodesItemSubsItem]
    next: GetProcessByIdResultHead | None
    customField: list[GetProcessByIdResultNodesItemcustomFieldItem]
    status: GetProcessByIdResultNodesItemStatus | None
    receipt: datetime.datetime | None


@dataclasses.dataclass
class GetProcessByIdResultNodesItemAlong(NoPydanticValidation):
    id: uuid.UUID
    title: str
    addenable: bool | None


@dataclasses.dataclass
class GetProcessByIdResultNodesItemAssignedItem(NoPydanticValidation):
    id: uuid.UUID
    title: str
    boss: GetProcessByIdResultNodesItemAssignedItemBoss | None
    staff: list[GetProcessByIdResultNodesItemAssignedItemBoss]


@dataclasses.dataclass
class GetProcessByIdResultNodesItemAssignedItemBoss(NoPydanticValidation):
    id: uuid.UUID
    login: str


@dataclasses.dataclass
class GetProcessByIdResultNodesItemStatus(NoPydanticValidation):
    id: uuid.UUID
    title: str
    color: str


@dataclasses.dataclass
class GetProcessByIdResultNodesItemSubsItem(NoPydanticValidation):
    id: uuid.UUID
    title: str
    start_verification: datetime.datetime | None
    comments: list[GetProcessByIdResultNodesItemSubsItemCommentsItem]
    fit: GetProcessByIdResultNodesItemSubsItemFit | None
    end_verification: datetime.datetime | None
    end_correction: datetime.datetime | None


@dataclasses.dataclass
class GetProcessByIdResultNodesItemSubsItemCommentsItem(NoPydanticValidation):
    id: uuid.UUID
    text_str: str
    author: GetProcessByIdResultNodesItemSubsItemCommentsItemAuthor | None
    answer: str | None


@dataclasses.dataclass
class GetProcessByIdResultNodesItemSubsItemCommentsItemAuthor(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class GetProcessByIdResultNodesItemSubsItemFit(NoPydanticValidation):
    id: uuid.UUID
    login: str
    FIO: str | None
    rights: list[GetProcessByIdResultNodesItemSubsItemFitRightsItem]


@dataclasses.dataclass
class GetProcessByIdResultNodesItemSubsItemFitRightsItem(NoPydanticValidation):
    id: uuid.UUID
    value: str


@dataclasses.dataclass
class GetProcessByIdResultNodesItemcustomFieldItem(NoPydanticValidation):
    id: uuid.UUID
    value: str
    titleField: GetProcessByIdResultNodesItemcustomFieldItemtitleField | None


@dataclasses.dataclass
class GetProcessByIdResultNodesItemcustomFieldItemtitleField(NoPydanticValidation):
    id: uuid.UUID
    value: str


@dataclasses.dataclass
class GetProcessByIdResultPriority(NoPydanticValidation):
    id: uuid.UUID
    value: str


@dataclasses.dataclass
class GetProcessByIdResultprocessType(NoPydanticValidation):
    id: uuid.UUID
    title: str


@dataclasses.dataclass
class GetProcessByIdResultrealiserGroup(NoPydanticValidation):
    id: uuid.UUID
    title: str
    boss: GetProcessByIdResultrealiserGroupBoss | None
    staff: list[GetProcessByIdResultrealiserGroupBoss]


@dataclasses.dataclass
class GetProcessByIdResultrealiserGroupBoss(NoPydanticValidation):
    id: uuid.UUID
    login: str


async def get_process_by_id(
    executor: edgedb.AsyncIOExecutor,
    *,
    process_id: uuid.UUID,
) -> GetProcessByIdResult | None:
    return await executor.query_single(
        """\
        with process_id := <uuid>$process_id,

        select Process {
          head: {
              id,
            },
            id,
            title,
            nodes: {
              id,
              title,
              assigned: {
                id, 
                title, 
                boss: {id, login}, 
                staff: {id, login}},
              along: {
                id,
                title,
                addenable,
              },
              addenable,
              subs: {
                id, 
                title, 
                start_verification, 
                comments: {
                  text_str,
                  author,
                  answer,
                },
                fit: {id, login, FIO, rights: {value}},
                end_verification,
                end_correction,
              },
              next: {id},
              customField: {
                value, 
                titleField: {value},
              },
              status: {title, color},
              receipt,
            },
            realiser: {id, login},
            realiserGroup: {id, title, boss: {login}, staff: {login}},
            priority: {value},
            passport_ref,
            processType: {title},
        } filter .id = process_id\
        """,
        process_id=process_id,
    )
