# AUTOGENERATED FROM 'app/queries/get_processes_by_realiser.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetProcessesByRealiserResult(NoPydanticValidation):
    id: uuid.UUID
    title: str
    nodes: list[GetProcessesByRealiserResultNodesItem]
    realiser: GetProcessesByRealiserResultNodesItemAssignedItemBoss | None
    realiserGroup: GetProcessesByRealiserResultrealiserGroup | None
    priority: GetProcessesByRealiserResultPriority | None
    passport_ref: str | None
    processType: GetProcessesByRealiserResultprocessType | None


@dataclasses.dataclass
class GetProcessesByRealiserResultNodesItem(NoPydanticValidation):
    id: uuid.UUID
    title: str
    assigned: list[GetProcessesByRealiserResultNodesItemAssignedItem]
    along: GetProcessesByRealiserResultNodesItemAlong | None
    addenable: bool | None
    subs: list[GetProcessesByRealiserResultNodesItemSubsItem]
    next: GetProcessesByRealiserResultNodesItemNext | None
    customField: list[GetProcessesByRealiserResultNodesItemcustomFieldItem]
    status: GetProcessesByRealiserResultNodesItemStatus | None
    receipt: datetime.datetime | None


@dataclasses.dataclass
class GetProcessesByRealiserResultNodesItemAlong(NoPydanticValidation):
    id: uuid.UUID
    title: str
    addenable: bool | None


@dataclasses.dataclass
class GetProcessesByRealiserResultNodesItemAssignedItem(NoPydanticValidation):
    id: uuid.UUID
    title: str
    boss: GetProcessesByRealiserResultNodesItemAssignedItemBoss | None
    staff: list[GetProcessesByRealiserResultNodesItemAssignedItemBoss]


@dataclasses.dataclass
class GetProcessesByRealiserResultNodesItemAssignedItemBoss(NoPydanticValidation):
    id: uuid.UUID
    login: str


@dataclasses.dataclass
class GetProcessesByRealiserResultNodesItemNext(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class GetProcessesByRealiserResultNodesItemStatus(NoPydanticValidation):
    id: uuid.UUID
    title: str
    color: str


@dataclasses.dataclass
class GetProcessesByRealiserResultNodesItemSubsItem(NoPydanticValidation):
    id: uuid.UUID
    title: str
    start_verification: datetime.datetime | None
    comments: list[GetProcessesByRealiserResultNodesItemSubsItemCommentsItem]
    fit: GetProcessesByRealiserResultNodesItemSubsItemFit | None
    end_verification: datetime.datetime | None
    end_correction: datetime.datetime | None


@dataclasses.dataclass
class GetProcessesByRealiserResultNodesItemSubsItemCommentsItem(NoPydanticValidation):
    id: uuid.UUID
    text_str: str
    author: GetProcessesByRealiserResultNodesItemSubsItemCommentsItemAuthor | None
    answer: str | None


@dataclasses.dataclass
class GetProcessesByRealiserResultNodesItemSubsItemCommentsItemAuthor(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class GetProcessesByRealiserResultNodesItemSubsItemFit(NoPydanticValidation):
    id: uuid.UUID
    login: str
    FIO: str | None
    rights: list[GetProcessesByRealiserResultNodesItemSubsItemFitRightsItem]


@dataclasses.dataclass
class GetProcessesByRealiserResultNodesItemSubsItemFitRightsItem(NoPydanticValidation):
    id: uuid.UUID
    value: str


@dataclasses.dataclass
class GetProcessesByRealiserResultNodesItemcustomFieldItem(NoPydanticValidation):
    id: uuid.UUID
    value: str
    titleField: GetProcessesByRealiserResultNodesItemcustomFieldItemtitleField | None


@dataclasses.dataclass
class GetProcessesByRealiserResultNodesItemcustomFieldItemtitleField(NoPydanticValidation):
    id: uuid.UUID
    value: str


@dataclasses.dataclass
class GetProcessesByRealiserResultPriority(NoPydanticValidation):
    id: uuid.UUID
    value: str


@dataclasses.dataclass
class GetProcessesByRealiserResultprocessType(NoPydanticValidation):
    id: uuid.UUID
    title: str


@dataclasses.dataclass
class GetProcessesByRealiserResultrealiserGroup(NoPydanticValidation):
    id: uuid.UUID
    title: str
    boss: GetProcessesByRealiserResultrealiserGroupBoss | None
    staff: list[GetProcessesByRealiserResultrealiserGroupBoss]


@dataclasses.dataclass
class GetProcessesByRealiserResultrealiserGroupBoss(NoPydanticValidation):
    id: uuid.UUID
    login: str


async def get_processes_by_realiser(
    executor: edgedb.AsyncIOExecutor,
    *,
    realiser_login: str,
) -> list[GetProcessesByRealiserResult]:
    return await executor.query(
        """\
        with realiser_login := <str>$realiser_login,
          realiser_user := (select User filter .login = realiser_login)

        select Process {
            id,
            title,
            nodes: {
              id,
              title,
              assigned: {
                id, 
                title, 
                boss: {id, login}, 
                staff: {id, login}},
              along: {
                id,
                title,
                addenable,
              },
              addenable,
              subs: {
                id, 
                title, 
                start_verification, 
                comments: {
                  text_str,
                  author,
                  answer,
                },
                fit: {id, login, FIO, rights: {value}},
                end_verification,
                end_correction,
              },
              next: {id},
              customField: {
                value, 
                titleField: {value},
              },
              status: {title, color},
              receipt,
            },
            realiser: {id, login},
            realiserGroup: {id, title, boss: {login}, staff: {login}},
            priority: {value},
            passport_ref,
            processType: {title},
        } filter .realiser = realiser_user;\
        """,
        realiser_login=realiser_login,
    )
