# AUTOGENERATED FROM 'app/queries/get_templates.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetTemplatesResult(NoPydanticValidation):
    id: uuid.UUID
    title: str


async def get_templates(
    executor: edgedb.AsyncIOExecutor,
) -> list[GetTemplatesResult]:
    return await executor.query(
        """\
        select Template {
          id,
          title,
        #   process: {
        #     id,
        #     title,
        #     nodes: {
        #       id,
        #       title,
        #       assigned: {
        #         id, 
        #         title, 
        #         boss: {id, login}, 
        #         staff: {id, login}},
        #       along: {
        #         id,
        #         title,
        #         addenable,
        #       },
        #       addenable,
        #       subs: {
        #         id, 
        #         title, 
        #         start_verification, 
        #         comments: {
        #           text_str,
        #           author,
        #           answer,
        #         },
        #         fit: {id, login, FIO, rights: {value}},
        #         end_verification,
        #         end_correction,
        #       },
        #       next: {id},
        #       customField: {
        #         value, 
        #         titleField: {value},
        #       },
        #       status: {title, color},
        #       receipt,
        #     },
        #     realiser: {id, login},
        #     realiserGroup: {id, title},
        #     priority: {value},
        #     passport_ref,
        #     processType: {title},
        #   }
        };\
        """,
    )
