# AUTOGENERATED FROM 'app/queries/get_process_from_template.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetProcessFromTemplateResult(NoPydanticValidation):
    id: uuid.UUID
    process: GetProcessFromTemplateResultProcess


@dataclasses.dataclass
class GetProcessFromTemplateResultProcess(NoPydanticValidation):
    head: GetProcessFromTemplateResultProcessHead | None
    id: uuid.UUID
    title: str
    nodes: list[GetProcessFromTemplateResultProcessNodesItem]
    realiser: GetProcessFromTemplateResultProcessNodesItemAssignedItemBoss | None
    realiserGroup: GetProcessFromTemplateResultProcessrealiserGroup | None
    priority: GetProcessFromTemplateResultProcessPriority | None
    passport_ref: str | None
    processType: GetProcessFromTemplateResultProcessprocessType | None


@dataclasses.dataclass
class GetProcessFromTemplateResultProcessHead(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class GetProcessFromTemplateResultProcessNodesItem(NoPydanticValidation):
    id: uuid.UUID
    title: str
    assigned: list[GetProcessFromTemplateResultProcessNodesItemAssignedItem]
    along: GetProcessFromTemplateResultProcessNodesItemAlong | None
    addenable: bool | None
    subs: list[GetProcessFromTemplateResultProcessNodesItemSubsItem]
    next: GetProcessFromTemplateResultProcessHead | None
    customField: list[GetProcessFromTemplateResultProcessNodesItemcustomFieldItem]
    status: GetProcessFromTemplateResultProcessNodesItemStatus | None
    receipt: datetime.datetime | None


@dataclasses.dataclass
class GetProcessFromTemplateResultProcessNodesItemAlong(NoPydanticValidation):
    id: uuid.UUID
    title: str
    addenable: bool | None


@dataclasses.dataclass
class GetProcessFromTemplateResultProcessNodesItemAssignedItem(NoPydanticValidation):
    id: uuid.UUID
    title: str
    boss: GetProcessFromTemplateResultProcessNodesItemAssignedItemBoss | None
    staff: list[GetProcessFromTemplateResultProcessNodesItemAssignedItemBoss]


@dataclasses.dataclass
class GetProcessFromTemplateResultProcessNodesItemAssignedItemBoss(NoPydanticValidation):
    id: uuid.UUID
    login: str


@dataclasses.dataclass
class GetProcessFromTemplateResultProcessNodesItemStatus(NoPydanticValidation):
    id: uuid.UUID
    title: str
    color: str


@dataclasses.dataclass
class GetProcessFromTemplateResultProcessNodesItemSubsItem(NoPydanticValidation):
    id: uuid.UUID
    title: str
    start_verification: datetime.datetime | None
    comments: list[GetProcessFromTemplateResultProcessNodesItemSubsItemCommentsItem]
    fit: GetProcessFromTemplateResultProcessNodesItemSubsItemFit | None
    end_verification: datetime.datetime | None
    end_correction: datetime.datetime | None


@dataclasses.dataclass
class GetProcessFromTemplateResultProcessNodesItemSubsItemCommentsItem(NoPydanticValidation):
    id: uuid.UUID
    text_str: str
    author: GetProcessFromTemplateResultProcessNodesItemSubsItemCommentsItemAuthor | None
    answer: str | None


@dataclasses.dataclass
class GetProcessFromTemplateResultProcessNodesItemSubsItemCommentsItemAuthor(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class GetProcessFromTemplateResultProcessNodesItemSubsItemFit(NoPydanticValidation):
    id: uuid.UUID
    login: str
    FIO: str | None
    rights: list[GetProcessFromTemplateResultProcessNodesItemSubsItemFitRightsItem]


@dataclasses.dataclass
class GetProcessFromTemplateResultProcessNodesItemSubsItemFitRightsItem(NoPydanticValidation):
    id: uuid.UUID
    value: str


@dataclasses.dataclass
class GetProcessFromTemplateResultProcessNodesItemcustomFieldItem(NoPydanticValidation):
    id: uuid.UUID
    value: str
    titleField: GetProcessFromTemplateResultProcessNodesItemcustomFieldItemtitleField | None


@dataclasses.dataclass
class GetProcessFromTemplateResultProcessNodesItemcustomFieldItemtitleField(NoPydanticValidation):
    id: uuid.UUID
    value: str


@dataclasses.dataclass
class GetProcessFromTemplateResultProcessPriority(NoPydanticValidation):
    id: uuid.UUID
    value: str


@dataclasses.dataclass
class GetProcessFromTemplateResultProcessprocessType(NoPydanticValidation):
    id: uuid.UUID
    title: str


@dataclasses.dataclass
class GetProcessFromTemplateResultProcessrealiserGroup(NoPydanticValidation):
    id: uuid.UUID
    title: str


async def get_process_from_template(
    executor: edgedb.AsyncIOExecutor,
    *,
    template_id: uuid.UUID,
) -> GetProcessFromTemplateResult | None:
    return await executor.query_single(
        """\
        with template_id := <uuid>$template_id,

        select Template {
          process: {
            head: {
              id,
            },
            id,
            title,
            nodes: {
              id,
              title,
              assigned: {
                id, 
                title, 
                boss: {id, login}, 
                staff: {id, login}},
              along: {
                id,
                title,
                addenable,
              },
              addenable,
              subs: {
                id, 
                title, 
                start_verification, 
                comments: {
                  text_str,
                  author,
                  answer,
                },
                fit: {id, login, FIO, rights: {value}},
                end_verification,
                end_correction,
              },
              next: {id},
              customField: {
                value, 
                titleField: {value},
              },
              status: {title, color},
              receipt,
            },
            realiser: {id, login},
            realiserGroup: {id, title},
            priority: {value},
            passport_ref,
            processType: {title},
          }
        } filter .id = template_id;\
        """,
        template_id=template_id,
    )
