# AUTOGENERATED FROM 'app/queries/start_node.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class StartNodeResult(NoPydanticValidation):
    id: uuid.UUID
    along: StartNodeResultAlong | None


@dataclasses.dataclass
class StartNodeResultAlong(NoPydanticValidation):
    id: uuid.UUID


async def start_node(
    executor: edgedb.AsyncIOExecutor,
    *,
    node_id: uuid.UUID,
    rec_time: datetime.datetime,
    new_status_title: str,
) -> StartNodeResult | None:
    return await executor.query_single(
        """\
        with node_id := <uuid>$node_id, rec_time := <datetime>$rec_time, new_status_title := <str>$new_status_title,

        select (
          update Node
          filter .id = node_id
          set {
            status := (select Status filter .title = new_status_title),
            receipt := rec_time,
          }
        ) {id, along};\
        """,
        node_id=node_id,
        rec_time=rec_time,
        new_status_title=new_status_title,
    )
