# AUTOGENERATED FROM 'app/queries/update_assigned_notification.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateAssignedNotificationResult(NoPydanticValidation):
    id: uuid.UUID


async def update_assigned_notification(
    executor: edgedb.AsyncIOExecutor,
    *,
    process_id: uuid.UUID,
) -> list[UpdateAssignedNotificationResult]:
    return await executor.query(
        """\
        with process_id := <uuid>$process_id,
          process := (select Process filter .id = process_id),
          assigned := process.nodes.assigned,

        for i in assigned union (
          insert Notification {
            to_department := i,
            new_assign := process,
          }
        )\
        """,
        process_id=process_id,
    )
