# AUTOGENERATED FROM 'app/queries/update_subnode_fit.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateSubnodeFitResult(NoPydanticValidation):
    id: uuid.UUID


async def update_subnode_fit(
    executor: edgedb.AsyncIOExecutor,
    *,
    login: str,
    subnode_id: uuid.UUID,
) -> UpdateSubnodeFitResult | None:
    return await executor.query_single(
        """\
        with login := <str>$login,
          user := (select User filter .login = login),
          subnode_id := <uuid>$subnode_id,
        update SubNode
        filter .id = subnode_id
        set {
          fit := user,
        }\
        """,
        login=login,
        subnode_id=subnode_id,
    )
