# AUTOGENERATED FROM 'app/queries/update_process_head_node.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateProcessHeadNodeResult(NoPydanticValidation):
    id: uuid.UUID


async def update_process_head_node(
    executor: edgedb.AsyncIOExecutor,
    *,
    head_id: uuid.UUID,
    process_id: uuid.UUID,
) -> UpdateProcessHeadNodeResult | None:
    return await executor.query_single(
        """\
        with 
          head := (select Node filter .id = <uuid>$head_id),
          process_id := <uuid>$process_id,

        select (
          update Process
          filter .id = process_id
          set {
            head := head,
          }
        ) {id};\
        """,
        head_id=head_id,
        process_id=process_id,
    )
