# AUTOGENERATED FROM 'app/queries/update_subnode_end_correction.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateSubnodeEndCorrectionResult(NoPydanticValidation):
    id: uuid.UUID


async def update_subnode_end_correction(
    executor: edgedb.AsyncIOExecutor,
    *,
    subnode_id: uuid.UUID,
    datetime: datetime.datetime,
) -> UpdateSubnodeEndCorrectionResult | None:
    return await executor.query_single(
        """\
        with subnode_id := <uuid>$subnode_id,
          date :=  <datetime>$datetime
        select (
          update SubNode
            filter .id = subnode_id
            set {
              end_correction := date,
            }
        ) {id};\
        """,
        subnode_id=subnode_id,
        datetime=datetime,
    )
