# AUTOGENERATED FROM 'app/queries/update_node_along.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateNodeAlongResult(NoPydanticValidation):
    id: uuid.UUID


async def update_node_along(
    executor: edgedb.AsyncIOExecutor,
    *,
    node_id: uuid.UUID,
    along_id: uuid.UUID,
) -> UpdateNodeAlongResult | None:
    return await executor.query_single(
        """\
        with node_id := <uuid>$node_id, along_id := <uuid>$along_id,
          node := (select Node filter .id = along_id),

        select (
          update Node
          filter .id = node_id
          set {
            along := node,
          }
        ) {id};\
        """,
        node_id=node_id,
        along_id=along_id,
    )
