# AUTOGENERATED FROM 'app/queries/update_node_next.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateNodeNextResult(NoPydanticValidation):
    id: uuid.UUID


async def update_node_next(
    executor: edgedb.AsyncIOExecutor,
    *,
    node_id: uuid.UUID,
    next_id: uuid.UUID,
) -> UpdateNodeNextResult | None:
    return await executor.query_single(
        """\
        with node_id := <uuid>$node_id, next_id := <uuid>$next_id,
          node := (select Node filter .id = next_id),

        select (
          update Node
          filter .id = node_id
          set {
            next := node,
          }
        ) {id};\
        """,
        node_id=node_id,
        next_id=next_id,
    )
